service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
