service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
  STAGE: ${opt:stage}
  myRegion:
    prod: us-west-2
    dev: us-west-1

provider:
  name: aws
  runtime: python3.6
  region: ${self:custom.myRegion.${opt:stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
